import type { ToolEntry } from "./tool-index.js";

/**
 * Full tool registry data for Keplr MCP Server.
 *
 * Each tool from REFERENCE.md is classified by category, ecosystem, risk level,
 * and search keywords. This registry powers the meta-tools (search-tools,
 * describe-tools) for dynamic tool discovery.
 */
export const TOOL_REGISTRY: ToolEntry[] = [
  // ─── Account Management (common) ────────────────────────────
  {
    name: "onboarding-status",
    description: "Check wallet setup progress (checklist, next steps)",
    category: "account-management",
    ecosystem: "common",
    risk: "safe",
    keywords: ["onboarding", "setup", "status", "checklist", "wallet"],
  },
  {
    name: "create-account",
    description: "Create a new wallet with BIP39 mnemonic",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["create", "account", "wallet", "mnemonic", "new"],
  },
  {
    name: "import-account",
    description: "Import an existing wallet from mnemonic",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["import", "account", "wallet", "mnemonic", "restore"],
  },
  {
    name: "list-accounts",
    description: "List all accounts with active status",
    category: "account-management",
    ecosystem: "common",
    risk: "safe",
    keywords: ["list", "accounts", "wallet", "active"],
  },
  {
    name: "switch-account",
    description: "Switch the active account",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["switch", "account", "active", "change"],
  },
  {
    name: "rename-account",
    description: "Rename an account",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["rename", "account", "name", "label"],
  },
  {
    name: "delete-account",
    description: "Delete an account (requires confirmation)",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["delete", "account", "remove", "wallet"],
  },
  {
    name: "export-mnemonic",
    description: "Export the mnemonic (recovery phrase) for an account",
    category: "account-management",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["export", "mnemonic", "backup", "recovery", "phrase", "seed"],
  },
  {
    name: "get-account-addresses",
    description: "Get all ecosystem addresses for the active account",
    category: "account-management",
    ecosystem: "common",
    risk: "safe",
    keywords: ["address", "account", "ecosystem", "get"],
  },
  {
    name: "check-vault-health",
    description:
      "Check vault integrity and repair orphaned/corrupt/dangling vault files",
    category: "account-management",
    ecosystem: "common",
    risk: "mixed",
    keywords: [
      "vault",
      "health",
      "integrity",
      "repair",
      "backup",
      "restore",
      "orphan",
      "corrupt",
      "keychain",
    ],
  },

  // ─── Authentication (common) ─────────────────────────────────
  {
    name: "auth-status",
    description: "Check authentication settings (Biometric, TOTP)",
    category: "authentication",
    ecosystem: "common",
    risk: "safe",
    keywords: ["auth", "status", "biometric", "totp", "security"],
  },
  {
    name: "auth-enable",
    description: "Enable authentication system",
    category: "authentication",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["auth", "enable", "activate", "security"],
  },
  {
    name: "auth-disable",
    description: "Disable authentication system",
    category: "authentication",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["auth", "disable", "deactivate", "security"],
  },
  {
    name: "auth-setup",
    description: "Set up authentication provider (biometric or TOTP)",
    category: "authentication",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["auth", "setup", "provider", "biometric", "totp"],
  },
  {
    name: "auth-verify-setup",
    description: "Complete TOTP setup with verification code",
    category: "authentication",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["auth", "verify", "totp", "code", "setup"],
  },
  {
    name: "auth-available-methods",
    description: "List available authentication methods for an action",
    category: "authentication",
    ecosystem: "common",
    risk: "safe",
    keywords: ["auth", "methods", "available", "options"],
  },
  {
    name: "auth-provider-disable",
    description: "Disable a specific authentication provider",
    category: "authentication",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["auth", "provider", "disable", "biometric", "totp"],
  },

  // ─── Transaction Confirmation (common) ───────────────────────
  {
    name: "confirm-action",
    description: "Execute a pending transaction with confirmation token",
    category: "transaction-confirm",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["confirm", "transaction", "execute", "approve", "token"],
  },
  {
    name: "list-pending-actions",
    description: "List pending transactions awaiting confirmation",
    category: "transaction-confirm",
    ecosystem: "common",
    risk: "safe",
    keywords: ["pending", "transactions", "list", "queue"],
  },
  {
    name: "cancel-pending-action",
    description: "Cancel a pending transaction",
    category: "transaction-confirm",
    ecosystem: "common",
    risk: "destructive",
    keywords: ["cancel", "pending", "transaction", "reject"],
  },
  {
    name: "list-transaction-history",
    description:
      "View past transaction history with status, chain, and results",
    category: "transaction-confirm",
    ecosystem: "common",
    risk: "safe",
    keywords: ["history", "transaction", "past", "recent", "log"],
  },
  {
    name: "get-portfolio",
    description:
      "Get unified portfolio (Cosmos chains, USD prices via CoinGecko)",
    category: "transaction-confirm",
    ecosystem: "common",
    risk: "safe",
    keywords: ["portfolio", "balance", "usd", "price", "overview"],
  },

  // ─── Cosmos Query (cosmos) ───────────────────────────────────
  {
    name: "list-cosmos-chains",
    description: "List supported Cosmos chains",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["cosmos", "chains", "list", "supported"],
  },
  {
    name: "get-cosmos-address",
    description: "Get wallet address for a specific Cosmos chain",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["cosmos", "address", "wallet", "chain"],
  },
  {
    name: "get-balances",
    description: "Query token balances",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["balance", "token", "query", "amount", "cosmos"],
  },
  {
    name: "get-staking-info",
    description: "Query staking delegations and rewards",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["staking", "delegation", "rewards", "info", "cosmos"],
  },
  {
    name: "list-validators",
    description: "List validators with commission and voting power",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["validators", "list", "commission", "voting", "cosmos"],
  },
  {
    name: "get-unbonding",
    description: "Query unbonding delegations",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["unbonding", "delegation", "unstaking", "query"],
  },
  {
    name: "list-proposals",
    description: "List governance proposals",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["proposals", "governance", "list", "vote", "cosmos"],
  },
  {
    name: "get-proposal",
    description: "Get detailed information about a specific proposal",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["proposal", "governance", "detail", "info"],
  },
  {
    name: "list-fee-tokens",
    description: "List fee tokens for a chain",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["fee", "tokens", "list", "gas", "chain"],
  },
  {
    name: "get-transaction-status",
    description: "Check transaction status by hash",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["transaction", "status", "hash", "check", "cosmos"],
  },
  {
    name: "list-ibc-channels",
    description: "List IBC channels",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["ibc", "channels", "list", "transfer", "cosmos"],
  },
  {
    name: "get-transaction-history",
    description: "Query transaction history",
    category: "cosmos-query",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["transaction", "history", "list", "recent"],
  },

  // ─── Cosmos Transaction (cosmos) ─────────────────────────────
  {
    name: "send-tokens",
    description: "Send tokens to another address",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["send", "tokens", "transfer", "cosmos", "pay"],
  },
  {
    name: "ibc-transfer",
    description: "IBC cross-chain token transfer",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["ibc", "transfer", "cross-chain", "bridge", "cosmos"],
  },
  {
    name: "delegate",
    description: "Delegate tokens to a validator (staking)",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["delegate", "stake", "validator", "cosmos"],
  },
  {
    name: "undelegate",
    description:
      "Undelegate tokens from a validator (unbonding period applies)",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["undelegate", "unstake", "unbond", "validator"],
  },
  {
    name: "redelegate",
    description: "Redelegate tokens between validators (instant move)",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["redelegate", "validator", "move", "switch", "stake"],
  },
  {
    name: "claim-rewards",
    description: "Claim staking rewards from a specific validator",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["claim", "rewards", "staking", "validator"],
  },
  {
    name: "claim-all-rewards",
    description: "Claim all staking rewards from all validators",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["claim", "all", "rewards", "staking", "batch"],
  },
  {
    name: "vote-governance",
    description: "Vote on a governance proposal",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["vote", "governance", "proposal", "cosmos"],
  },
  {
    name: "cancel-unbonding",
    description: "Cancel an in-progress unbonding delegation",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["cancel", "unbonding", "delegation", "undo"],
  },

  // ─── CosmWasm Smart Contracts (cosmos) ───────────────────────
  {
    name: "cosmwasm-query",
    description: "Query contract state (read-only)",
    category: "cosmwasm",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["cosmwasm", "query", "contract", "state", "read"],
  },
  {
    name: "cosmwasm-contract-info",
    description: "Query contract metadata",
    category: "cosmwasm",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["cosmwasm", "contract", "info", "metadata"],
  },
  {
    name: "cosmwasm-execute",
    description: "Execute a smart contract function",
    category: "cosmwasm",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["cosmwasm", "execute", "contract", "write", "invoke"],
  },
  {
    name: "cosmwasm-instantiate",
    description: "Instantiate a new contract instance",
    category: "cosmwasm",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["cosmwasm", "instantiate", "contract", "deploy", "create"],
  },
  {
    name: "cosmwasm-list-contracts",
    description: "List CosmWasm contract addresses by code ID",
    category: "cosmwasm",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["cosmwasm", "list", "contracts", "code", "discover", "search"],
  },

  // ─── Cosmos Signing (cosmos) ─────────────────────────────────
  {
    name: "cosmos-sign-arbitrary",
    description: "Sign an arbitrary message with ADR-36 (off-chain auth)",
    category: "cosmos-signing",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["sign", "arbitrary", "adr36", "message", "cosmos"],
  },
  {
    name: "cosmos-verify-signature",
    description: "Verify an ADR-36 signature",
    category: "cosmos-signing",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["verify", "signature", "adr36", "cosmos"],
  },

  // ─── Adapter & Protocol Info (common) ───────────────────────────────
  {
    name: "list-installed-adapters",
    description: "List installed ecosystem adapters",
    category: "meta",
    ecosystem: "common",
    risk: "safe",
    keywords: ["adapters", "installed", "list", "ecosystem", "plugins"],
  },
  // ─── DeFi: Osmosis (cosmos) ─────────────────────────────────
  {
    name: "osmosis-quote",
    description: "Get Osmosis DEX swap quote via Skip Routes API",
    category: "defi-osmosis",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["osmosis", "quote", "swap", "dex", "price", "skip", "multi-hop"],
  },
  {
    name: "osmosis-swap",
    description: "Execute Osmosis DEX token swap via Skip Routes API",
    category: "defi-osmosis",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: [
      "osmosis",
      "swap",
      "dex",
      "trade",
      "exchange",
      "skip",
      "multi-hop",
    ],
  },

  // ─── Cosmos Multi-Action (cosmos) ─────────────────────────────
  {
    name: "multi-action-create",
    description:
      "Start a multi-action transaction to combine multiple Cosmos operations atomically",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "batch", "create", "atomic"],
  },
  {
    name: "multi-action-add",
    description: "Add an action to a multi-action transaction",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "add", "batch"],
  },
  {
    name: "multi-action-remove",
    description: "Remove an action from a multi-action transaction by index",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "remove", "delete"],
  },
  {
    name: "multi-action-preview",
    description:
      "Preview and simulate a multi-action transaction (gas, fees, balance changes)",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "preview", "simulate", "gas"],
  },
  {
    name: "multi-action-execute",
    description: "Execute all actions in a multi-action transaction",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "destructive",
    keywords: ["multi", "action", "execute", "submit", "batch"],
  },
  {
    name: "multi-action-cancel",
    description: "Cancel and discard a multi-action transaction",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "cancel", "discard"],
  },
  {
    name: "multi-action-list",
    description: "List all pending multi-action transactions",
    category: "cosmos-transaction",
    ecosystem: "cosmos",
    risk: "safe",
    keywords: ["multi", "action", "list", "pending"],
  },

  // ─── Keplr RPC (common) ─────────────────────────────────────
  {
    name: "kr_validate_key",
    description: "Validate an existing Keplr Endpoints API key",
    category: "keplr-rpc",
    ecosystem: "common",
    risk: "safe",
    keywords: ["keplr", "api", "key", "validate", "check"],
  },
  {
    name: "kr_get_payment_link",
    description: "Get a Stripe payment link to add credits",
    category: "keplr-rpc",
    ecosystem: "common",
    risk: "safe",
    keywords: ["keplr", "payment", "stripe", "credits", "buy"],
  },
  {
    name: "kr_get_usage_summary",
    description:
      "Get usage summary (balance, requests, credits, per-chain breakdown)",
    category: "keplr-rpc",
    ecosystem: "common",
    risk: "safe",
    keywords: [
      "keplr",
      "usage",
      "summary",
      "balance",
      "credits",
      "requests",
      "stats",
    ],
  },
  {
    name: "kr_get_usage_history",
    description: "Get usage history with optional date/chain/endpoint filters",
    category: "keplr-rpc",
    ecosystem: "common",
    risk: "safe",
    keywords: ["keplr", "usage", "history", "timeline", "filter"],
  },
  {
    name: "kr_list_chains",
    description: "List all chains available on Keplr Endpoints",
    category: "keplr-rpc",
    ecosystem: "common",
    risk: "safe",
    keywords: ["keplr", "chains", "list", "endpoints", "available"],
  },

  // ─── Meta-tools (common) ─────────────────────────────────────
  {
    name: "search-tools",
    description: "Search available tools by keyword, category, or ecosystem",
    category: "meta",
    ecosystem: "common",
    risk: "safe",
    keywords: ["search", "find", "discover", "tools", "help"],
  },
  {
    name: "describe-tools",
    description:
      "Get full details (parameters, category, risk) for specific tools",
    category: "meta",
    ecosystem: "common",
    risk: "safe",
    keywords: ["describe", "details", "schema", "parameters", "usage"],
  },
];
